version: "3.9"
services:
  booking-postgres:
    image: postgres:latest
    container_name: booking-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - private-network
    volumes:
      - booking_service_data:/var/lib/postgresql/data

  hotel-postgres:
    image: postgres:latest
    container_name: hotel-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - private-network
    volumes:
      - hotel_service_data:/var/lib/postgresql/data

  hotel-service:
    build: hotel-service/
    container_name: hotel-service
    depends_on:
      - hotel-postgres
    environment:
      HOTEL_SERVICE_SERVER_PORT: 8081
      HOTEL_SERVICE_SERVER_HOST: localhost
      HOTEL_SERVICE_SERVER_GRPC_PORT: 50051
      HOTEL_SERVICE_SERVER_GRPC_HOST: hotel-service
      HOTEL_SERVICE_DB_HOST: hotel-postgres
      HOTEL_SERVICE_DB_PORT: 5432
      HOTEL_SERVICE_DB_NAME: postgres
      HOTEL_SERVICE_DB_USER: postgres
      HOTEL_SERVICE_DB_PASSWORD: postgres
      HOTEL_SERVICE_DB_MIGRATIONS_PATH: migrations/migrations.sql
      HOTEL_SERVICE_APP_SHUTDOWN_TIMEOUT: 5s
    networks:
      - private-network
    ports:
      - "8081:8081"

  booking-service:
    build: booking-service/
    container_name: booking-service
    depends_on:
      - booking-postgres
      - hotel-service
    environment:
      BOOKING_SERVICE_SERVER_PORT: 8080
      BOOKING_SERVICE_SERVER_HOST: localhost
      BOOKING_SERVICE_DB_HOST: booking-postgres
      BOOKING_SERVICE_DB_PORT: 5432
      BOOKING_SERVICE_DB_NAME: postgres
      BOOKING_SERVICE_DB_USER: postgres
      BOOKING_SERVICE_DB_PASSWORD: postgres
      BOOKING_SERVICE_DB_MIGRATIONS: migrations/migrations.sql
      BOOKING_SERVICE_GRPC_HOST: booking-service
      BOOKING_SERVICE_GRPC_PORT: 50052
      BOOKING_SERVICE_APP_SHUTDOWN_TIMEOUT: 20s
      HOTEL_SERVICE_SERVER_HOST: hotel-service
      HOTEL_SERVICE_SERVER_PORT: 50051
    networks:
      - private-network
    ports:
      - "8080:8080"

volumes:
  booking_service_data:
  hotel_service_data:

networks:
  private-network: {}
