// command to generate (run from payment-system dir)
// protoc --go_out=. --go-grpc_out=. api/api_v1.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: api/api_v1.proto

package api_v1pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentSystem_AddPayment_FullMethodName = "/api_v1.PaymentSystem/AddPayment"
)

// PaymentSystemClient is the client API for PaymentSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentSystemClient interface {
	AddPayment(ctx context.Context, in *AddPaymentRequest, opts ...grpc.CallOption) (*AddPaymentResponse, error)
}

type paymentSystemClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentSystemClient(cc grpc.ClientConnInterface) PaymentSystemClient {
	return &paymentSystemClient{cc}
}

func (c *paymentSystemClient) AddPayment(ctx context.Context, in *AddPaymentRequest, opts ...grpc.CallOption) (*AddPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPaymentResponse)
	err := c.cc.Invoke(ctx, PaymentSystem_AddPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentSystemServer is the server API for PaymentSystem service.
// All implementations must embed UnimplementedPaymentSystemServer
// for forward compatibility.
type PaymentSystemServer interface {
	AddPayment(context.Context, *AddPaymentRequest) (*AddPaymentResponse, error)
	mustEmbedUnimplementedPaymentSystemServer()
}

// UnimplementedPaymentSystemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentSystemServer struct{}

func (UnimplementedPaymentSystemServer) AddPayment(context.Context, *AddPaymentRequest) (*AddPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPayment not implemented")
}
func (UnimplementedPaymentSystemServer) mustEmbedUnimplementedPaymentSystemServer() {}
func (UnimplementedPaymentSystemServer) testEmbeddedByValue()                       {}

// UnsafePaymentSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentSystemServer will
// result in compilation errors.
type UnsafePaymentSystemServer interface {
	mustEmbedUnimplementedPaymentSystemServer()
}

func RegisterPaymentSystemServer(s grpc.ServiceRegistrar, srv PaymentSystemServer) {
	// If the following call pancis, it indicates UnimplementedPaymentSystemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentSystem_ServiceDesc, srv)
}

func _PaymentSystem_AddPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentSystemServer).AddPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentSystem_AddPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentSystemServer).AddPayment(ctx, req.(*AddPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentSystem_ServiceDesc is the grpc.ServiceDesc for PaymentSystem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentSystem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api_v1.PaymentSystem",
	HandlerType: (*PaymentSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPayment",
			Handler:    _PaymentSystem_AddPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api_v1.proto",
}
