// command to generate (run from payment-system dir)
// protoc --go_out=. --go-grpc_out=. api/api_v1.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: api/api_v1.proto

package api_v1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPaymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingId   string  `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	BookingCost float32 `protobuf:"fixed32,2,opt,name=booking_cost,json=bookingCost,proto3" json:"booking_cost,omitempty"`
}

func (x *AddPaymentRequest) Reset() {
	*x = AddPaymentRequest{}
	mi := &file_api_api_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentRequest) ProtoMessage() {}

func (x *AddPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaymentRequest.ProtoReflect.Descriptor instead.
func (*AddPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_api_v1_proto_rawDescGZIP(), []int{0}
}

func (x *AddPaymentRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *AddPaymentRequest) GetBookingCost() float32 {
	if x != nil {
		return x.BookingCost
	}
	return 0
}

type AddPaymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlForPay string `protobuf:"bytes,1,opt,name=url_for_pay,json=urlForPay,proto3" json:"url_for_pay,omitempty"`
}

func (x *AddPaymentResponse) Reset() {
	*x = AddPaymentResponse{}
	mi := &file_api_api_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentResponse) ProtoMessage() {}

func (x *AddPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaymentResponse.ProtoReflect.Descriptor instead.
func (*AddPaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_api_v1_proto_rawDescGZIP(), []int{1}
}

func (x *AddPaymentResponse) GetUrlForPay() string {
	if x != nil {
		return x.UrlForPay
	}
	return ""
}

var File_api_api_v1_proto protoreflect.FileDescriptor

var file_api_api_v1_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x5f, 0x76, 0x31, 0x22, 0x55, 0x0a, 0x11, 0x41, 0x64,
	0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x73,
	0x74, 0x22, 0x34, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x75, 0x72, 0x6c, 0x5f, 0x66,
	0x6f, 0x72, 0x5f, 0x70, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x72,
	0x6c, 0x46, 0x6f, 0x72, 0x50, 0x61, 0x79, 0x32, 0x54, 0x0a, 0x0d, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x43, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x50,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x76, 0x31, 0x2e,
	0x41, 0x64, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a,
	0x0c, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x76, 0x31, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_api_v1_proto_rawDescOnce sync.Once
	file_api_api_v1_proto_rawDescData = file_api_api_v1_proto_rawDesc
)

func file_api_api_v1_proto_rawDescGZIP() []byte {
	file_api_api_v1_proto_rawDescOnce.Do(func() {
		file_api_api_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_api_v1_proto_rawDescData)
	})
	return file_api_api_v1_proto_rawDescData
}

var file_api_api_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_api_v1_proto_goTypes = []any{
	(*AddPaymentRequest)(nil),  // 0: api_v1.AddPaymentRequest
	(*AddPaymentResponse)(nil), // 1: api_v1.AddPaymentResponse
}
var file_api_api_v1_proto_depIdxs = []int32{
	0, // 0: api_v1.PaymentSystem.AddPayment:input_type -> api_v1.AddPaymentRequest
	1, // 1: api_v1.PaymentSystem.AddPayment:output_type -> api_v1.AddPaymentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_api_v1_proto_init() }
func file_api_api_v1_proto_init() {
	if File_api_api_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_api_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_api_v1_proto_goTypes,
		DependencyIndexes: file_api_api_v1_proto_depIdxs,
		MessageInfos:      file_api_api_v1_proto_msgTypes,
	}.Build()
	File_api_api_v1_proto = out.File
	file_api_api_v1_proto_rawDesc = nil
	file_api_api_v1_proto_goTypes = nil
	file_api_api_v1_proto_depIdxs = nil
}
