version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: hotel-service-postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "data"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
